fix: GitHub workflows to use the new 3-state dependency flags
Most of the docker images are updated to fetch the system version
of the required packages. The exceptions are:
- Ubuntu 18.04: Aubio is only available in version 0.4.5 whereas
  Performous requires version 0.4.9 at least,
- Windows: Aubio CMake finder is not working properly and the following
  error is thrown:
      CMake Error at C:/Program Files/CMake/share/cmake-3.23/Modules/FindPkgConfig.cmake:603 (message):
      Error:   A required package was not found
      Call Stack (most recent call first):
        C:/Program Files/CMake/share/cmake-3.23/Modules/FindPkgConfig.cmake:825 (_pkg_check_modules_internal)
        cmake/Modules/FindAubio.cmake:15 (pkg_check_modules)
        D:/a/performous/performous/vcpkg/scripts/buildsystems/vcpkg.cmake:805 (_find_package)
        game/CMakeLists.txt:110 (find_package)